spring.application.name=cinevault

tmdb.api.url=https://api.themoviedb.org/3
tmdb.api.token=${TMDB_TOKEN}

#DB config
spring.datasource.url=jdbc:postgresql://localhost:5432/cinevault
spring.datasource.username=cinevault
spring.datasource.password=cinevault123
